// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgvivenmospbswmdltcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ndml2ZW5tb3NwYnN3bWRsdGN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMDMzNjcsImV4cCI6MjA1ODY3OTM2N30.BZcrukdyWa2JT-JoY4ngRUW35WpbHozE-kiSzWYz41o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);